# Generated by Django 5.2 on 2025-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=128),
        ),
    ]
