# Generated by Django 5.2 on 2025-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=255, verbose_name='Technology Name')),
                ('program', models.JSONField(default=list, help_text='List of technology-related programs', verbose_name='Program')),
                ('business', models.CharField(max_length=255, verbose_name='Business')),
                ('site', models.CharField(max_length=255, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Plant Programme',
                'verbose_name_plural': 'Plants Programmes',
                'db_table': 'plants_programmes',
            },
        ),
    ]
