# Generated by Django 5.2 on 2025-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_cluster', models.CharField(max_length=255, verbose_name='Technology Cluster')),
                ('coc_export_name', models.CharField(blank=True, max_length=255, verbose_name='CoC Expert Name')),
                ('product_domains', models.CharField(blank=True, max_length=255, verbose_name='Product Domains')),
                ('technology_domains', models.CharField(blank=True, max_length=255, verbose_name='Technology Domains')),
                ('tmd_names', models.JSONField(blank=True, default=list, help_text='List of TMD names', verbose_name='TDM Name')),
                ('technology_name', models.CharField(max_length=255, verbose_name='Technology Name')),
                ('technology_description', models.TextField(blank=True, verbose_name='Technology Description')),
                ('current_trl', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TRL 1'), (2, 'TRL 2'), (3, 'TRL 3'), (4, 'TRL 4'), (5, 'TRL 5'), (6, 'TRL 6'), (7, 'TRL 7'), (8, 'TRL 8'), (9, 'TRL 9')], null=True, verbose_name='Current TRL (1-9)')),
                ('trl1_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL1 Year')),
                ('trl2_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL2 Year')),
                ('trl3_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL3 Year')),
                ('trl4_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL4 Year')),
                ('trl5_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL5 Year')),
                ('trl6_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL6 Year')),
                ('trl7_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL7 Year')),
                ('trl8_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL8 Year')),
                ('trl9_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL9 Year')),
                ('trl1_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL1 Cost')),
                ('trl2_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL2 Cost')),
                ('trl3_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL3 Cost')),
                ('trl4_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL4 Cost')),
                ('trl5_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL5 Cost')),
                ('trl6_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL6 Cost')),
                ('trl7_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL7 Cost')),
                ('trl8_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL8 Cost')),
                ('trl9_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL9 Cost')),
                ('tech_cluster_dependencies', models.JSONField(blank=True, default=list, help_text='Same list of values as Technology Cluster', verbose_name='Tech. Cluster Dependencies')),
                ('fom_type', models.CharField(blank=True, max_length=100, verbose_name='FoM Type')),
                ('fom_value_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='FoM Value (%)')),
                ('targeted_programmes', models.JSONField(blank=True, default=list, help_text='List of targeted programmes (same taxonomy as PlantProgrammes.program)', verbose_name='Targeted Programmes')),
                ('ac_application', models.CharField(blank=True, max_length=255, verbose_name='A/C Application')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'db_table': 'technologies',
            },
        ),
    ]
