# Generated by Django 5.2 on 2025-11-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0002_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='coc_export_name',
            new_name='coc_expert_name',
        ),
    ]
