# Generated by Django 5.2 on 2025-11-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0003_rename_coc_export_name_technology_coc_expert_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='tmd_names',
            new_name='tdm_names',
        ),
    ]
