# Generated by Django 5.2 on 2025-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0004_rename_tmd_names_technology_tdm_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosmos_dvs', models.CharField(max_length=255, verbose_name='Cosmos DVSs')),
                ('cosmos_dvs_resp_name', models.CharField(max_length=255, verbose_name='Cosmos DVS Responsible Name')),
                ('coc_clusters', models.CharField(max_length=255, verbose_name='CoC Clusters')),
                ('coc_expertise', models.CharField(max_length=255, verbose_name='CoC Expertise')),
                ('coc_expert_name', models.CharField(max_length=255, verbose_name='CoC Expert Name')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'db_table': 'strategies',
            },
        ),
    ]
