# Generated by Django 5.2 on 2025-12-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0005_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_processes', models.CharField(max_length=255, verbose_name='Group Processes')),
                ('subgroup_processes', models.CharField(max_length=255, verbose_name='Sub-Group Processes')),
                ('process_name', models.CharField(max_length=255, verbose_name='Process Name')),
                ('process_resp_name', models.CharField(max_length=255, verbose_name='Process Responsible Name')),
                ('technology_name', models.CharField(max_length=255, verbose_name='Technology Name')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'db_table': 'processes',
            },
        ),
    ]
