# Generated by Django 5.2 on 2025-12-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0006_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255, verbose_name='Project ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('project_description', models.CharField(max_length=255, verbose_name='Project Description')),
                ('project_benefits', models.CharField(max_length=255, verbose_name='Project Benefits')),
                ('ads_group', models.CharField(max_length=255, verbose_name='Airbus Group Division')),
                ('programmes', models.JSONField(default=list, help_text='Programmes - Plant', verbose_name='Programmes')),
                ('synergies', models.CharField(max_length=255, verbose_name='Synergies Project Name AG')),
                ('project_leader', models.CharField(max_length=255, verbose_name='Project Leader')),
                ('other_team_members', models.CharField(max_length=255, verbose_name='Other Team Members')),
                ('project_start_date', models.DateField(blank=True, null=True, verbose_name='Project Start Date')),
                ('project_end_date', models.DateField(blank=True, null=True, verbose_name='Project End Date')),
                ('project_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Project Total Cost')),
                ('project_funding_call', models.CharField(max_length=255, verbose_name='Project Funding Call Name')),
                ('project_maturity', models.CharField(max_length=255, verbose_name='Project Maturity')),
                ('project_running_status', models.CharField(max_length=255, verbose_name='Project Running Status')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
    ]
