# Generated by Django 5.2 on 2025-12-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0009_alter_plantprogramme_technology_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trl_number', models.PositiveSmallIntegerField(choices=[(1, 'TRL 1'), (2, 'TRL 2'), (3, 'TRL 3'), (4, 'TRL 4'), (5, 'TRL 5'), (6, 'TRL 6'), (7, 'TRL 7'), (8, 'TRL 8'), (9, 'TRL 9')], verbose_name='TRL Number')),
                ('trl_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TRL Year')),
                ('trl_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='TRL Cost')),
            ],
            options={
                'verbose_name': 'TRL',
                'verbose_name_plural': 'TRLs',
                'db_table': 'trls',
            },
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl1_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl1_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl2_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl2_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl3_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl3_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl4_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl4_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl5_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl5_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl6_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl6_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl7_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl7_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl8_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl8_year',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl9_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='trl9_year',
        ),
        migrations.AddField(
            model_name='technology',
            name='trl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iidb.trl', verbose_name='TRL'),
        ),
    ]
