# Generated by Django 5.2 on 2026-01-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0011_technology_trls_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprogramme',
            name='technology_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iidb.technology', to_field='technology_name', verbose_name='Technology Name'),
        ),
    ]
