# Generated by Django 5.2 on 2026-01-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0012_alter_plantprogramme_technology_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='coc_expert_name',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='tdm_names',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='technology_cluster',
        ),
        migrations.AddField(
            model_name='technology',
            name='digital_technology_cluster',
            field=models.CharField(blank=True, max_length=255, verbose_name='Digital Technology Cluster'),
        ),
        migrations.AddField(
            model_name='technology',
            name='physical_technology_cluster',
            field=models.CharField(blank=True, max_length=255, verbose_name='Physical Technology Cluster'),
        ),
    ]
