# Generated by Django 5.2 on 2026-02-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidb', '0013_remove_technology_coc_expert_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='product_domains',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='tech_cluster_dependencies',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='technology_domains',
        ),
        migrations.AddField(
            model_name='technology',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, help_text='Same list of values as Technology Cluster', verbose_name='Dependencies'),
        ),
        migrations.AddField(
            model_name='technology',
            name='product_roadmap',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product Roadmap'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_roadmap',
            field=models.CharField(blank=True, max_length=255, verbose_name='Technology Roadmap'),
        ),
    ]
